---
- name: Install development tools
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Ensure basic packages are installed
      ansible.builtin.package:
        name:
          - git
          - curl
          - wget
        state: present
