---
- name: Install Microsoft Edge on Ubuntu
  hosts: localhost
  connection: local
  become: true
  vars:
    ms_repo_keyring_path: /etc/apt/keyrings/microsoft.gpg
  tasks:
    - name: Download Microsoft GPG key to secure keyring
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: "{{ ms_repo_keyring_path }}"
        mode: '0644'

    - name: Add Microsoft Edge repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main
        state: present
        filename: microsoft-edge

    - name: Install Microsoft Edge
      ansible.builtin.apt:
        name: microsoft-edge-stable
        state: present
        update_cache: true
