- name: Install Microsoft Intune (Ubuntu 24.04)
  hosts: localhost
  connection: local
  become: true
  vars:
    ms_repo_keyring_path: /usr/share/keyrings/microsoft.gpg
  tasks:
  - name: Ensure required packages are installed
    apt:
      name:
      - curl
      - ca-certificates
      - gnupg
      - apt-transport-https
      state: present

  - name: Download Microsoft GPG key to secure keyring
    get_url:
      url: https://packages.microsoft.com/keys/microsoft.asc
      dest: "{{ ms_repo_keyring_path }}"
      mode: '0644'

  - name: Add Microsoft Intune repository with signed-by
    apt_repository:
      repo: "deb [arch=amd64 signed-by={{ ms_repo_keyring_path }}] https://packages.microsoft.com/ubuntu/24.04/prod noble main"
      filename: microsoft-intune
      state: present

  - name: Install Microsoft Intune agent
    apt:
      name: intune-portal
      state: present
      update_cache: true
