- name: Install Microsoft Intune (Ubuntu 24.04)
  hosts: localhost
  connection: local
  become: true
  vars:
    ms_repo_keyring_path: /etc/apt/keyrings/microsoft.gpg
  tasks:
    - name: Download Microsoft GPG key to secure keyring
      ansible.builtin.get_url:
        url: https://packages.microsoft.com/keys/microsoft.asc
        dest: "{{ ms_repo_keyring_path }}"
        mode: '0644'

    - name: Add Microsoft Intune repository with signed-by
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/24.04/prod noble main"
        filename: microsoft-intune
        state: present

    - name: Install Microsoft Intune agent
      ansible.builtin.apt:
        name: intune-portal
        state: present
        update_cache: true
