---
- name: Install tool
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Ensure basic diagnotic tools are installed
      ansible.builtin.package:
        name:
          - htop
          - vim
          - nmap
          - ansible-lint
        state: present
